### PR TITLE
Add Ukrainian translation

### PR DESCRIPTION
**Pull request by thevladyslav**
Note: I didn't translate `log_event` strings

### CODE REVIEW

**Comment by mikemee** [comment]
@AlexDibrivnyy Does this look ok to you?  Please approve if so. Thanks!

**Comment by mikemee** [comment]
@personaljesusua thanks for the contribution!

**Comment by AlexDibrivnyy** [comment]
Hi @personaljesusua, Thank you for your time. Glad to see Ukrainian translation here.

I reviewed your version and I have a couple of comments regarding it. 
Here are some corrections:
```
<resources>
    <string name="egab_leave_review">Залишити відгук</string>
    <string name="egab_contact_support">З\'єднатися з підтримкою</string>
    <string name="egab_try_other_apps">Спробувати інші додатки</string>
    <string name="egab_version">Версія</string>
    <string name="egab_author">Автор</string>
    
    <string name="egab_web_label">Веб</string>
    <string name="egab_acknowledgements">Подяка</string>
    <string name="egab_privacy_policy">Політика приватності</string>
    <string name="egab_about_screen_title">Про додаток</string>
    <string name="egab_share">Поділитися</string>
	
    <string name="egab_can_not_open">У Вас немає додатка, який може відкрити це посилання</string>
    <string name="egab_email_body_prompt">Будь ласка, напишіть Ваше запитання тут: </string>
    <string name="egab_guide">Правила гри</string>

</resources>

```

Can you please take a look and let me know if you agree? If yes, please incorporate these changes, no - let me know what is wrong.

Thank you.

**Review by mikemee — CHANGES_REQUESTED** [review]
Please address @AlexDibrivnyy comments, thanks!

**Comment by thevladyslav** [comment]
@AlexDibrivnyy, I updated strings with your edits

**Review by AlexDibrivnyy — CHANGES_REQUESTED** [review]
@personaljesusua Thank you for your changes. But I see that lint failed. Can you, please, check why? Possible you need to restore `egab_..._log_event` strings or just add `translatable="false"` to original string.xml.

**Comment by mikemee** [comment]
@personaljesusua the build is failing. Can you fix it please and we'll merge?

**Comment by mikemee** [comment]
@AlexDibrivnyy please review and merge if you're ok with it. Thanks @personaljesusua!

**Review by AlexDibrivnyy — APPROVED** [review]
Approved.

**Review by mikemee — APPROVED** [review]

**Pull request merged**
