### PR TITLE
Empty cards are no longer displayed

### PR DESCRIPTION
**Pull request by Ninjaman494**
Previously, cards with no items in them still go displayed in About Activity. I fixed this by adding checks to see if a card has an item to display before adding it to About Activity.

### CODE REVIEW

**Comment by mikemee** [comment]
@Ninjaman494 Thanks so much!  It looks like there are some PMD errors. Do you mind fixing those so the build passes please?

**Comment by Ninjaman494** [comment]
I looked at the errors and I'm not sure what's wrong.  Two are about useless parentheses at these two lines:
```
if((config.buildType != null && !TextUtils.isEmpty(config.appPublisher) && !TextUtils.isEmpty(config.packageName))
                || (!TextUtils.isEmpty(config.companyHtmlPath) && !TextUtils.isEmpty(config.aboutLabelTitle))){
```
But I think removing the parentheses would change the if statement's meaning.

The other is Possible God class at line 1, which is just the package declaration.
`package com.eggheadgames.aboutbox.activity;`

I might be missing something though, I don't have much experience with pmd reports, or builds tests at all for that matter.

**Comment by mikemee** [comment]
@Ninjaman494 Thanks for taking a look. I've never seen PMD get parenthesis mixed up. Perhaps it's worthwhile to add an intermediate variable there to simplify the test.

Hmm, "Possible God Class" usually means we've crossed some (arbitrary) line to do with the number of functions, nesting etc.

**Comment by Ninjaman494** [comment]
Fixed the parenthesis errors. I'm not sure how to fix the God Class one. I could consolidate the if statements in one place, since they're pretty much identical to the ones that happen in the private build methods, but I think that would just make the code more complex. Any suggestions?

**Comment by mikemee** [comment]
A great improvement!  For God Class, generally I just "play with the code" to see what might remove the error. Usually it's a sign that the entire class is too big or too complex and that it should be refactored into two classes. But since it wasn't an error before, and is now, chances are there's something simpler than that possible.

Feel free to see if you can improve it. If I get a chance I will try too, but probably not until late this week.

Thanks!

**Comment by mikemee** [comment]
Fixed in #54. Closing.

@Ninjaman494 thanks for the inspiration. Without this PR I doubt this would have happened. Sorry it took so long to complete.

**Comment by Ninjaman494** [comment]
No problem! It's my fault for dropping the ball on this. Life kinda got in the way and I completely forgot about this PR. I'm happy someone else was able pick it up and finish it.

**Pull request closed without merging**
